### PR TITLE
upgraded sbtpgp plugin

### PR DESCRIPTION
**Pull request by nfma**

### CODE REVIEW

**Comment by duncancrawford** [comment]
Can we not just remove this plugin?

**Comment by nfma** [comment]
that makes everyone import it to their own project, not sure how useful that would be...

we can release this plugin in a new version and let people gradually upgrade.

**Comment by duncancrawford** [comment]
Why do they need to import this plugin?

**Comment by nfma** [comment]
oh, you meant the sbt-utils one rather than the gpg one...

I thought it would help with the publishing (in general not just sonatype), but I've not dig too much into this, I can try and check if I can get the simple-reactivemongo working without it...

**Comment by nfma** [comment]
there seems to be a bunch of default build settings that are imported via this plugin, not sure if removing this plugin (given that lots of projects use it) doesn't not create more work than fixing this problem

**Comment by duncancrawford** [comment]
Is the reference to the sbt-pgp plugin needed in this repo? If not then let's delete it from /plugins/plugins.sbt rather than upgrade it

**Comment by nfma** [comment]
if we move the plugin to a global configuration then we don't need it neither here nor anywhere, but then we make our lives harder if we need to upgrade because that leads to a big-bang upgrade.

we can't delete it from here because this plugin needs it for its own publishing, as this is an open sourced project.

**Comment by duncancrawford** [comment]
I don't agree but happy to be told otherwise. Lets talk

**Pull request closed without merging**
